### ISSUE TITLE
TypeError: this.el.select2 is not a function

### ISSUE THREAD

**Issue by afgarcia86** [rkit/react-select2-wrapper#36]
I am pulling my hair out trying to figure out why select2 stopped working for me. My best guess is that a package I updated is conflicting with this one. However I figured I would ask here to see if there is an easy way to resolve the issue. Thanks for your help.

**Comment by afgarcia86** [comment]
Actually I was able to resolve it after finding (https://github.com/rkit/react-select2-wrapper/issues/31). I remove the node_modules inside the react-select2-wrapper (jquery). Then I included that version of jquery in my package and I guess its not being included twice or in the incorrect order now.

**Comment by nsisodiya** [comment]
https://github.com/dopeddude/react-select2-wrapper/commit/98ca7c52b53687bbf93edc6f5bc891dec289dba2

**Comment by dopeddude** [comment]
The reason for the above issue was in the following dependency tree

```
├─┬ react-select2-wrapper@0.6.1
│ ├─┬ select2@4.0.3
│ │ ├── almond@0.3.2
│ │ └── jquery-mousewheel@3.1.13
│ └── shallow-equal-fuzzy@0.0.2
```

`jquery-mousewheel@3.1.13` depends on the `"jquery": ">=1.2.2"` and thus it brings jquery 3.0 while the `react-select2-wrapper@0.6.1` still depends on the `"jquery": "^2.1.4",` and hence the version mismatch. And hence the issue probably due to twice/incorrect loading of jquery.

So, with the above commit as mentioned by @nsisodiya , in my local I was able to resolve the issue.

As the package compiled output was required for the local testing so I went with the following steps:
```
In my root `package.json` updated the repo reference as
"react-select2-wrapper": "dopeddude/react-select2-wrapper"
And then run the following commands
$ cd node_modules/react-select2-wrapper/
$ npm i
$ npm run compile
$ mv node_modules/ node_modules_bak/
$ cd ../../
```
In future, When the `react-select2-wrapper` library itself upgrades to the latest jquery version, and thus they publish it to npm. Then the above steps will not be needed and repo reference can be reverted.

**Comment by afgarcia86** [comment]
Sounds good to me I can close this if you would like.

**Comment by dopeddude** [comment]
@afgarcia86 : yes, please close the issue. The respective PR "https://github.com/rkit/react-select2-wrapper/pull/38" is merged and now you can refer to the latest published version as `1.0.0-beta1` on your package.json.

**Comment by rkit** [comment]
Guys, tomorrow I'll release 1.0.0 release (not beta)

**Comment by afgarcia86** [comment]
I tested the beta, it worked for me :shipit:

**Comment by aberonni** [comment]
I'm having this same issue in tests while using the latest version. For some reason I get it only inside tests with jest. If I force select2 version to 4.0.3 I don't encounter the issue anymore.

Later I will try and see if I can reproduce consistently.

**Comment by scottybollinger** [comment]
I also am still receiving this issue with `1.0.4-beta`

**Comment by CWSites** [comment]
I'm having the same issue with Jest unit tests when mounting a component with `Select2`, I tried bumping `select2` to version `4.0.3` locally but that didn't fix anything for me.
